[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "workshop-transcription"
version = "0.1.0"
dependencies = []

[project.scripts]
align-cherokee = "transcription.timestamping.align_cli:main"

[tool.setuptools.packages.find]
include = ["transcription*"]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | data
    | colab-script-rips
    | archive
  )/
  | scripts/from_elan_to_wav_and_gsheet\.py
  | transcription/audio/extract_from_elan\.py
  | test_topk\.py
)
'''

